import type { Metadata } from "next";
import "./globals.css";
import Header from "./Components/Header/header";
import Footer from "./Components/Footer/footer";

export const metadata: Metadata = {
  title: "Projeto Irmão Animal",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Header />
        <div>{children}</div>
        <Footer />
      </body>
    </html>
  );
}
